# Note: add the following to your vscode settings to allow the vscode graphql extension to function properly
# "graphql-config.load.rootDir": "client",
# "graphql-config.dotEnvPath": "client/.env",
schema:
  - http://localhost:8080/v1/graphql:
      headers:
        x-hasura-admin-secret: ${HASURA_GRAPHQL_ADMIN_SECRET}
documents:
  - src/**/*.{gql,graphql}
  - src-graphql/**/*.{gql,graphql}
extensions:
  codegen:
    overwrite: true
    generates:
      src-graphql/graphql.d.ts:
        plugins:
          - add:
              content: "import * as CustomScalars from './custom-scalars.d';"
          - typescript:
              scalars:
                balance_direction: CustomScalars.BalanceDirection
                bpchar: string
                smallint: number
                Int: number
                bigint: bigint
                timestamptz: string
                tstzrange: string
          - typescript-operations
      src-graphql/:
        preset: near-operation-file
        presetConfig:
          baseTypesPath: graphql.d.ts
          extension: .generated.ts
        plugins:
          - typescript-vue-urql:
              typesPrefix: Types.
              skipTypename: true # wether to add __typename to the generated types
      src-graphql/urql-introspected-schema.ts:
        plugins:
          - urql-introspection
