CREATE TABLE public.exchange_rate_history (
    id INTEGER NOT NULL,
    source_currency_id CHARACTER(3) NOT NULL,
    target_currency_id CHARACTER(3) NOT NULL,
    source_currency_rate INTEGER NOT NULL CHECK (source_currency_rate > 0),
    target_currency_rate INTEGER NOT NULL CHECK (target_currency_rate > 0),
    effective_period TSTZRANGE NOT NULL,
    created_by_user_id INTEGER,
    updated_by_user_id INTEGER,
    deleted_by_user_id INTEGER,
    sys_period TSTZRANGE NOT NULL,
    CHECK (source_currency_id <> target_currency_id),
    EXCLUDE USING gist (id WITH =, sys_period WITH &&)
);

CREATE TABLE public.exchange_rate (
    id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    PRIMARY KEY (id),
    EXCLUDE USING gist (source_currency_id WITH =, target_currency_id WITH =, effective_period WITH &&),
    CHECK (source_currency_id <> target_currency_id),
    CHECK (source_currency_rate > 0),
    CHECK (target_currency_rate > 0),
    FOREIGN KEY (source_currency_id) REFERENCES public.currency (id) ON UPDATE RESTRICT ON DELETE CASCADE,
    FOREIGN KEY (target_currency_id) REFERENCES public.currency (id) ON UPDATE RESTRICT ON DELETE CASCADE,
    FOREIGN KEY (created_by_user_id) REFERENCES public.user (id) ON UPDATE RESTRICT ON DELETE RESTRICT,
    FOREIGN KEY (updated_by_user_id) REFERENCES public.user (id) ON UPDATE RESTRICT ON DELETE RESTRICT,
    FOREIGN KEY (deleted_by_user_id) REFERENCES public.user (id) ON UPDATE RESTRICT ON DELETE RESTRICT
) INHERITS (public.exchange_rate_history);

-- triggers run in alphabetical order, numbers in their name ensure proper execution order
CREATE TRIGGER trigger_001_supress_redundant_updates
BEFORE UPDATE ON public.exchange_rate
FOR EACH ROW EXECUTE FUNCTION suppress_redundant_updates_trigger();

CREATE TRIGGER trigger_002_versioning
BEFORE INSERT OR UPDATE OR DELETE ON public.exchange_rate
FOR EACH ROW EXECUTE FUNCTION versioning('sys_period', 'public.exchange_rate_history', true);

COMMENT ON TABLE  public.exchange_rate                                   IS 'Exchange Rate';
COMMENT ON COLUMN public.exchange_rate.id                                IS 'Primary key';
COMMENT ON COLUMN public.exchange_rate.source_currency_id                IS 'Currency we are converting from. Foreign Key to currency table, Currency ISO 4217 code, 3 characters long.';
COMMENT ON COLUMN public.exchange_rate.target_currency_id                IS 'Currency we are converting to. Foreign Key to currency table, Currency ISO 4217 code, 3 characters long.';
COMMENT ON COLUMN public.exchange_rate.source_currency_rate              IS 'Fractional units of the source currency equal to fractiona units of the target currency in target_currency_rate. Must be greater than 0.';
COMMENT ON COLUMN public.exchange_rate.target_currency_rate              IS 'Fractional units of the target currency equal to fractiona units of the source currency in source_currency_rate. Must be greater than 0.';
COMMENT ON COLUMN public.exchange_rate.effective_period                  IS 'Period during which this exchange rate will be valid. Multiple exchange rates can exist at the same time, but they may not overlap.';

COMMENT ON COLUMN public.exchange_rate.created_by_user_id                IS 'id of user who created this record';
COMMENT ON COLUMN public.exchange_rate.updated_by_user_id                IS 'id of user who updated this record';
COMMENT ON COLUMN public.exchange_rate.deleted_by_user_id                IS 'id of user who deleted this record';
COMMENT ON COLUMN public.exchange_rate.sys_period                        IS 'Effective system period for this record. Use in conjunction with primary key to retrieve past versions from history table';


COMMENT ON TABLE  public.exchange_rate_history                           IS 'Exchange Rate History';
COMMENT ON COLUMN public.exchange_rate_history.id                        IS 'Primary key';
COMMENT ON COLUMN public.exchange_rate_history.source_currency_id        IS 'Currency we are converting from. Foreign Key to currency table, Currency ISO 4217 code, 3 characters long.';
COMMENT ON COLUMN public.exchange_rate_history.target_currency_id        IS 'Currency we are converting to. Foreign Key to currency table, Currency ISO 4217 code, 3 characters long.';
COMMENT ON COLUMN public.exchange_rate_history.source_currency_rate      IS 'Fractional units of the source currency equal to fractiona units of the target currency in target_currency_rate. Must be greater than 0.';
COMMENT ON COLUMN public.exchange_rate_history.target_currency_rate      IS 'Fractional units of the target currency equal to fractiona units of the source currency in source_currency_rate. Must be greater than 0.';
COMMENT ON COLUMN public.exchange_rate_history.effective_period          IS 'Period during which this exchange rate will be valid. Multiple exchange rates can exist at the same time, but they may not overlap.';

COMMENT ON COLUMN public.exchange_rate_history.created_by_user_id        IS 'id of user who created this record';
COMMENT ON COLUMN public.exchange_rate_history.updated_by_user_id        IS 'id of user who updated this record';
COMMENT ON COLUMN public.exchange_rate_history.deleted_by_user_id        IS 'id of user who deleted this record';
COMMENT ON COLUMN public.exchange_rate_history.sys_period                IS 'Effective system period for this record. Use in conjunction with primary key to retrieve past versions from history table';

