version: "3.8"
services:
  postgres:
    volumes:
      - postgres_data:/var/lib/postgresql/data
  business-logic:
    image: business-logic:dev
    build:
      args:
        NODE_ENV: development
    command: npm run dev
    environment:
      NODE_ENV: development
    volumes:
      - ./business-logic/src:/usr/app/src
volumes:
  postgres_data:
