mutation UpdateUserById($id: Int!, $update: user_set_input!) {
  update: update_user_by_pk(pk_columns: { id: $id }, _set: $update) {
    id
    username
    display_name
  }
}

mutation UpdateUserPassword(
  $user_id: Int!
  $session_id: Int!
  $password: String!
) {
  update: update_user_by_pk(
    pk_columns: { id: $user_id }
    _set: { password: $password }
  ) {
    id
    username
    display_name
  }
  delete_session(
    where: { user_id: { _eq: $user_id }, id: { _neq: $session_id } }
  ) {
    affected_rows
  }
}
