CREATE TABLE public.account_history (
    id INTEGER NOT NULL,
    code TEXT NOT NULL,
    name TEXT NOT NULL,
    description TEXT,
    normal_balance public.balance_direction NOT NULL,
    parent_title_account_id INTEGER NOT NULL,

    created_by_user_id INTEGER,
    updated_by_user_id INTEGER,
    deleted_by_user_id INTEGER,
    sys_period TSTZRANGE NOT NULL,
    EXCLUDE USING gist (id WITH =, sys_period WITH &&)
);

CREATE TABLE public.account (
    id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    PRIMARY KEY (id),
    UNIQUE (code),
    UNIQUE (name),
    FOREIGN KEY (parent_title_account_id) REFERENCES public.title_account (id) ON UPDATE RESTRICT ON DELETE CASCADE,
    FOREIGN KEY (created_by_user_id) REFERENCES public.user (id) ON UPDATE RESTRICT ON DELETE RESTRICT,
    FOREIGN KEY (updated_by_user_id) REFERENCES public.user (id) ON UPDATE RESTRICT ON DELETE RESTRICT,
    FOREIGN KEY (deleted_by_user_id) REFERENCES public.user (id) ON UPDATE RESTRICT ON DELETE RESTRICT
) INHERITS (public.account_history);

-- triggers run in alphabetical order, numbers in their name ensure proper execution order
CREATE TRIGGER trigger_001_supress_redundant_updates
BEFORE UPDATE ON public.account
FOR EACH ROW EXECUTE FUNCTION suppress_redundant_updates_trigger();

CREATE TRIGGER trigger_002_versioning
BEFORE INSERT OR UPDATE OR DELETE ON public.account
FOR EACH ROW EXECUTE FUNCTION versioning('sys_period', 'public.account_history', true);

COMMENT ON TABLE  public.account                                   IS 'Account';
COMMENT ON COLUMN public.account.id                                IS 'Primary Key';
COMMENT ON COLUMN public.account.code                              IS 'Surogate code. Unique';
COMMENT ON COLUMN public.account.name                              IS 'Full account name, Unique';
COMMENT ON COLUMN public.account.name                              IS 'Account description';
COMMENT ON COLUMN public.account.normal_balance                    IS 'Account Normal Balance. Either debit or credit';

COMMENT ON COLUMN public.account.created_by_user_id                IS 'id of user who created this record';
COMMENT ON COLUMN public.account.updated_by_user_id                IS 'id of user who updated this record';
COMMENT ON COLUMN public.account.deleted_by_user_id                IS 'id of user who deleted this record';
COMMENT ON COLUMN public.account.sys_period                        IS 'Effective system period for this record. Use in conjunction with primary key to retrieve past versions from history table';


COMMENT ON TABLE  public.account_history                           IS 'Account History';
COMMENT ON COLUMN public.account_history.id                        IS 'Primary Key';
COMMENT ON COLUMN public.account_history.code                      IS 'Surogate code. Unique';
COMMENT ON COLUMN public.account_history.name                      IS 'Full account name, Unique';
COMMENT ON COLUMN public.account_history.name                      IS 'Account description';
COMMENT ON COLUMN public.account_history.normal_balance            IS 'Account Normal Balance. Either debit or credit';

COMMENT ON COLUMN public.account_history.created_by_user_id        IS 'id of user who created this record';
COMMENT ON COLUMN public.account_history.updated_by_user_id        IS 'id of user who updated this record';
COMMENT ON COLUMN public.account_history.deleted_by_user_id        IS 'id of user who deleted this record';
COMMENT ON COLUMN public.account_history.sys_period                IS 'Effective system period for this record. Use in conjunction with primary key to retrieve past versions from history table';

